# Используем базовый образ CentOS
FROM centos:latest

# Устанавливаем необходимые пакеты
RUN apt-get -y install python3 
RUN apt-get -y install python3-pip 
RUN apt-get -y install unzip 

# Устанавливаем ChromeDriver
RUN wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip 
RUN unzip chromedriver_linux64.zip
RUN mv chromedriver /usr/local/bin/chromedriver 
RUN chmod +x /usr/local/bin/chromedriver 
RUN rm chromedriver_linux64.zip

# Устанавливаем Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm 
RUN apt-get -y localinstall google-chrome-stable_current_x86_64.rpm 
RUN rm google-chrome-stable_current_x86_64.rpm

# Копируем зависимости для тестов
COPY requirements.txt /app/requirements.txt

# Устанавливаем зависимости
WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt

# Копируем тестовый код
COPY . ./app

# Запускаем тесты
CMD ["python3", "tests/CAFAP/AIS_CAFAP/ais_cafap.py"]
