FROM python:3.8

RUN apt-get -y install python3
RUN apt_get -y install python3-pip



COPY . ./app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python3", "tests/CAFAP/AIS_CAFAP/ais_cafap.py"]